aws/aws-lambda-python-runtime-interface-client

- setup.py
*Issue #, if available:* n/a
* remove space prefix from url
* Uncomment prod/stable since it's a 1.0.0 release (?)
> Tidy setup.py

- setup.py
> Update minor release version to 1.1.0

- setup.py
Update version for releasing Curl version updates
> Update version for patch relase

- setup.py
-Updated minor version for release
> Update minor version for Release

- setup.py
- Corrected the next release version
> Correct the next release version

- awslambdaric/__init__.py
Bump version to include https://github.com/aws/aws-lambda-python-runtime-interface-client/commit/a6524b0cdc1baede55cfb6f3d1faf31ac4c8e214
> Bump version to 2.0.1

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
> Bump version to 2.0.4

- README.md
- setup.py
- tests/integration/codebuild/buildspec.os.alpine.yml
- tests/integration/codebuild/buildspec.os.amazonlinux.1.yml
- tests/integration/codebuild/buildspec.os.amazonlinux.2.yml
- tests/integration/codebuild/buildspec.os.centos.yml
- tests/integration/codebuild/buildspec.os.debian.yml
- tests/integration/codebuild/buildspec.os.ubuntu.yml
#85 
- Add python3.10 to tests and documentation.
> Add python3.10.

- README.md
- setup.py
- tests/integration/codebuild/buildspec.os.alpine.yml
- tests/integration/codebuild/buildspec.os.amazonlinux.1.yml
- tests/integration/codebuild/buildspec.os.amazonlinux.2.yml
- tests/integration/codebuild/buildspec.os.centos.yml
- tests/integration/codebuild/buildspec.os.debian.yml
- tests/integration/codebuild/buildspec.os.ubuntu.yml
#89 
- Add python3.11 to tests and documentation.
> Add python3.11

- .github/workflows/PULL_REQUEST_TEMPLATE.md
Create a pull request template
> Create pull request template.

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
Issue #, if available:
N/A
Description of changes:
Bump version to 2.0.6
Target (OCI, Managed Runtime, both):
N/A
> Bunp version to 2.0.6.

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
> Bump version to 2.0.7

- README.md
- setup.py
- tests/integration/codebuild/buildspec.os.alpine.yml
- tests/integration/codebuild/buildspec.os.amazonlinux.1.yml
- tests/integration/codebuild/buildspec.os.amazonlinux.2.yml
- tests/integration/codebuild/buildspec.os.centos.yml
- tests/integration/codebuild/buildspec.os.debian.yml
- tests/integration/codebuild/buildspec.os.ubuntu.yml
N/A
- Add python3.12 to tests and documentation.
Both
> Add Python3.12.

- requirements/base.txt
- tests/test_lambda_runtime_marshaller.py
N/A
Downgrade simplejson to 3.17.2
Both
> Downgrade to simplejson 3.17.2.

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
_Issue #, if available:_ N/A
_Description of changes:_ Bump version to 2.0.8
_Target (OCI, Managed Runtime, both):_ both
> Bump version to 2.0.8

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
N/a
Bump version to 2.0.9
Both.
> Bump version to 2.0.9

- awslambdaric/lambda_literals.py
N/a
Add a new line at end of runtime management controls warning message.
Both.
> Update format of unhandled exception warning message.

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
N/a
Bump version to 2.0.10
Both
> Bump version to 2.0.10.

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
N/a
- Bump version to 2.0.11.
N/a
> Bump to version 2.0.11.

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
Issue #, if available:
N/a
Description of changes:
Bump version to 2.0.12.
Target (OCI, Managed Runtime, both):
N/a
> Bump to version 2.0.12.

- awslambdaric/bootstrap.py
- tests/test_bootstrap.py
NA
Raise all init errors in init instead of suppressing them until the fist invoke
Both
> Raise all init errors in init instead of suppressing them until the fist invoke

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
NA
Bump version to `2.1.0`
Both
> Bump version to 2.1.0

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
> Update version to 2.2.1

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
_Issue #, if available: NA
_Description of changes:
Bump version to `3.0.0`
_Target (OCI, Managed Runtime, both): Both 
> Bump version to 3.0.0

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
N/a
Bump version to 3.0.1 
Both
> Bump to version 3.0.1.

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
N/a
- Bump to version 3.0.2.
Both
> Bump to version 3.0.2.

- RELEASE.CHANGELOG.md
- awslambdaric/__init__.py
> Bump to version 3.1.0
