- .pre-commit-config.yaml
This prevents Black from using Python 3.7+ only syntax when you still support for Python 3.6.
> Use Python 3.6 for Black

- .github/workflows/test-on-push-and-pr.yml
- test/integration/codebuild-local/codebuild_build.sh
- test/integration/codebuild-local/test_one.sh
- test/test_bootstrap.py
* Added GitHub workflow to run the required checks on push and pr
* Removed unnecessary `-it` option from `codebuild_build.sh` because it was causing `tty` error when running the GitHub action.
* Refactored some assertions in a test in order to be compatible with GitHub Actions environment
* Removed unnecessary `/tmp` path from `mktemp` command that was causing rights issues
> Include GitHub action on push and pr

- README.md
- test/integration/codebuild/buildspec.os.alpine.1.yml
- test/integration/codebuild/buildspec.os.alpine.2.yml
- test/integration/codebuild/buildspec.os.alpine.3.yml
- test/integration/codebuild/buildspec.os.amazonlinux.yml
- test/integration/codebuild/buildspec.os.centos.1.yml
- test/integration/codebuild/buildspec.os.centos.2.yml
- test/integration/codebuild/buildspec.os.debian.yml
- test/integration/codebuild/buildspec.os.ubuntu.1.yml
- test/integration/codebuild/buildspec.os.ubuntu.2.yml
- Added "docker login" for authenticating to dockerHub account while running integration tests. This will fix the docker hub rate limit error while pulling the images.
- Docker Hub credentials need to be set as CodeBuild environment variables as described in the README's Troubleshooting section.
- Added curl installation to fix below issue in Debian image
```
sh: 1: curl: not found
```
> Added 'docker login' to fix pull rate limit issue

- test/integration/docker/Dockerfile.echo.amazonlinux
- test/integration/docker/Dockerfile.echo.centos
- In the buildspec files for OS compatibility tests only the major.minor version of python is specified. Then, in the Dockerfile the latest patch version is fetched.
The problem with this is that it can happen that there will be a patch version not released yet, but there is a release candidate for that (at the moment it is for [Python 3.8.7](https://www.python.org/ftp/python/3.8.7/)). This will cause an error.
Modified so that every patch version is tried from the latest one to the earliest one until a valid one is found.
> Revise fetching latest patch version of python

- awslambdaric/bootstrap.py
- test/test_bootstrap.py
Fix for missing "errorMessage" field from exception response, when "errorMessage" field is "" or None, handled the same case for "errorType" and "stackTrace" fields in exception response.
Updated unit test case accordingly.
Tested by running test_bootstrap.py and integration test suite.
> errorMessage field is missing from exception response

- .gitignore
- awslambdaric/bootstrap.py
- requirements/dev.txt
- tests/test_bootstrap.py
Remove `imp` in favor of `importlib`
`imp` module is deprecated since Python 3.3
The previous implementation had some issues while trying to load python modules ( execute `__init__.py` files) when you specify a handler in a directory. 
By using `importlib` these issues go away and the implementation is way easier.
- Remove usages of `imp.find_module` and `imp.load_module` and use `importlib.import_module`.
- Relax `pylint` version since the pinned version wasn't supported by Python 3.8.
- Fix and improve tests.
**Source**
https://docs.python.org/3/library/imp.html#imp.find_module
> Deprecated since version 3.3: Use importlib.util.find_spec() instead unless Python 3.3 compatibility is required, in which case use importlib.find_loader(). For example usage of the former case, see the …
> Use importlib

- awslambdaric/runtime_client.cpp
- setup.py
`runtime_client` is holding the GIL (Global Interpreter Lock) while it is polling for the `runtime/invocation/next` invocation, which is meant to be an async I/O operation.
According to the [Python extension docs on Initialization, Finalization, and Threads](https://docs.python.org/3/c-api/init.html#thread-state-and-the-global-interpreter-lock), any blocking I/O should release the lock explicitly to allow other code to continue. This is especially true for extensions where developers (us, in this case) should manage releasing/reacquiring the lock.
> Without the lock, even the simplest operations could cause problems in a multi-threaded program: for example, when two threads simultaneously increment the reference count of the same object, the reference count could end up being incremented …
> Release GIL when polling Runtime API for next invocation

- awslambdaric/bootstrap.py
- tests/test_bootstrap.py
- Add request Id in error response
Customer can search for requestId in LogResults, and cloudwatch but getting it returned in error response relieve their pain for searching
> Add requestId in error response

- awslambdaric/bootstrap.py
- setup.py
- tests/test_bootstrap.py
- tests/test_built_in_module_name/sys.py
- tests/test_handler_with_slash/test_handler.py
#43
- Support for / in handler name
- Added test for the same
- Added the review comments from PR https://github.com/aws/aws-lambda-python-runtime-interface-client/pull/44
> Add Support for / in handler name 

- awslambdaric/bootstrap.py
- It impacted the error message in case user handler name is a/module1.handler, and the module was not found it would raise error as a.module1 not found rather than a/module1 is not found. Corrected this behavior
> Move the / to . replcement only for import_module call, error message was impacted

- awslambdaric/__init__.py
- awslambdaric/lambda_runtime_client.py
- setup.py
- tests/test_lambda_runtime_client.py
*Description of changes:*  
Remove importlib.metadata dependency & introduce `__version__` .
> Remove importlib.metadata dependency

- scripts/preinstall.sh
- scripts/update_deps.sh
*Issue #37:* 
Fix for the error _Cannot change ownership to uid 1515433866, gid 1896053708_ raised while installing from a container as root.
Indeed:
* High UIDs and GIDs are not accepted from Docker containers
* As root (only), by default, the *tar* command extracts files using the ownership described in the archive (not of the FS)
Adds tar option `--no-same-owner` so that the ownership is not forced in the destination and the python module can be installed as root from a container.
> (#37) Adds '--no-same-owner' option to all scripts tar commands

- awslambdaric/bootstrap.py
- tests/test_bootstrap.py
Utilize the fd directly rather than through opening its pseudo file in /proc, with this change it will be more compatible with different types of file descriptor including file descriptors of network sockets, while the old approach is kinda limited to files and pipes.
> Using the raw fd directly rather than opening the fd pseudo file

- awslambdaric/bootstrap.py
Milliseconds part of a log timestamp now padded with leading zeroes
> Add leading zeros to the milliseconds part of a log timestamp

- RELEASE.CHANGELOG.md
Add release changelog and backfill previous releases. 
> Add changelog

- awslambdaric/__main__.py
This change improves the error handling when running `awslambdaric` without a handler. Currently, the exception thrown is fairly non-specific: 
```
python -m awslambdaric
Traceback (most recent call last):
File "python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "awslambdaric/__main__.py", line 20, in <module>
main(sys.argv)
File "awslambdaric/__main__.py", line 13, in main
handler = args[1]
IndexError: list index out of range
```
The changes make the output a bit more human friendly 😄 :
```
python -m awslambdaric
Traceback (most recent call last):
File "python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File …
```
> Improve Exception Output for run with Missing Handler

- requirements/base.txt
This should complete a previous attempt to remove dependency on the
package, unblocking use of `awslambdaric` in projects that use a newer
version of `importlib-metadata`. Version 2 of `importlib-metadata` is
reasonably old - version 4.4 is present in Python 3.10 for instance.
Motivation for the change
----
I think issue #61 covers it well, but essentially it becomes difficult
to use `awslambdaric` in a virtualenv with other dependencies that
expect a newer version of `importlib-metadata`:
`awslambdaric` isn't supposed to need `importlib-metadata` anyway
----
Previous work (in August of 2021, with version 1.2.2) removed all
dependency on the `importlib-metadata` package, but accidentally left
`importlib-metadata` as a full dependency of this package:
- …
> Remove the importlib-metadata dependency

- awslambdaric/bootstrap.py
- awslambdaric/lambda_runtime_log_utils.py
- tests/test_bootstrap.py
- tests/test_lambda_context.py
- tests/test_lambda_runtime_client.py
*Description:*
This PR adds structured logging support for lambda functions.
Log format and level now encoded into message header. 
User are able to set format and level through the environment variables `AWS_LAMBDA_LOG_FORMAT` and `AWS_LAMBDA_LOG_LEVEL`.
> Emit logs in JSON format

- awslambdaric/bootstrap.py
- awslambdaric/lambda_runtime_log_utils.py
- tests/test_bootstrap.py
Use AWS_LAMBDA_LOG_LEVEL env var to set log level for text format
> Use AWS_LAMBDA_LOG_LEVEL env var to set log level for text format

- awslambdaric/lambda_runtime_client.py
Implicit `import ssl` is happening here: https://github.com/python/cpython/blob/main/Lib/http/client.py#L1431
`http.client` is only used to report a case of thrown Exception during init. It's not a general execution path, and it's not time-critical. Thus it makes sense to speed up cold starts by importing on-demand
> Lazily initialize http modules used for error handling

- awslambdaric/lambda_runtime_marshaller.py
- requirements/base.txt
- tests/test_lambda_runtime_marshaller.py
Fixes #87 and Fixes #62 
Make the `Encoder` class in `lambda_runtime_marshaller` use actual unicode characters in the encoded output instead of unicode escape sequences. This matters because unicode escape sequences contribute more bytes to the response size.
Also bump simplejson version for Python 3.9 compatibility.
> Use unicode chars instead of escape sequences in json encoder output and bump simplejson version

- awslambdaric/bootstrap.py
- awslambdaric/lambda_runtime_client.py
- awslambdaric/lambda_runtime_exception.py
- tests/test_lambda_runtime_client.py
- Tidy up changes added with PR#115 and limit it to only work with Pytho3.12 in Lambda.
_Target (OCI, Managed Runtime, both)_: OCI and Managed Runtime
> Tidy up changes added with PR#115 and limit it to only work with Python3.12 in Lambda.

- awslambdaric/lambda_runtime_client.py
- tests/test_bootstrap.py
_Description of changes:_ 
* Move ThreadPoolExecutor imports from lazy to "not as lazy". It offloads unnecessary work from actual invocations, especially the first one. Existing tests are already covering affected code paths and components
* ThreadPoolExecutor is still imported as a private dependency of a `LambdaRuntimeClient`, not exposing the symbols imported conditionally
* Fix tests - the latest runtimes have changed `unittest.mock.patch` behavior, when `sys.stdout` patching does not work as expected in certain combinations with other `@patch`'es in our testcases
_Target (OCI, Managed Runtime, both):_ Both
> Refactor conditional loading of ThreadPoolExecutor

- awslambdaric/bootstrap.py
- awslambdaric/lambda_literals.py
- awslambdaric/lambda_runtime_client.py
- tests/test_bootstrap.py
N/a
- Add warning message on unhandled exception during invoke to direct towards runtime management controls.
both
> Log warning on unhandled exception.

- requirements/base.txt
- tests/test_bootstrap.py
fixes #135
fixes #93 
fixes #62 
- Upgrades to `simplejson==3.18.4`
- Update unit test accordingly
```bash
make pr
make test
make test-smoke
make test-integ
```
Both
---
> Upgrade simplejson to `3.18.4`

- tests/integration/docker/Dockerfile.echo.alpine
Context: `libexecinfo-dev` couldn't be found on alpine
Changes: replaced `libexecinfo-dev` with `elfutils`. This change is taken from the NodeJS RIC.
https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/2ce88619fd176a5823bc5f38c5484d1cbdf95717/test/integration/docker/Dockerfile.echo.alpine#L11-L22
> Fix alpine image breaking due to missing dependencies and curl

- awslambdaric/lambda_runtime_marshaller.py
- requirements/base.txt
Fixes: #147
Description of changes:
Simplejson had a breaking change from 3.18.4 (existing) going to 3.19 where the default behaviour of the JSONEncoder changed with respect to NaN handling. We address that in a backwards compatible way by passing allow_nan=True.
_Target (OCI, Managed Runtime, both):_ both
> Relax simplejson dependency and keep it backwards compatible

- tests/integration/codebuild-local/codebuild_build.sh
The PR mirrors the change done in the NodeJS ric. This PR ensures failures in actions are visible. Followup PR will fix the tests as done in NodeJS.
> Use latest codebuild version

- awslambdaric/bootstrap.py
- awslambdaric/lambda_runtime_client.py
- tests/test_lambda_runtime_client.py
NA
Propagate error type in header when reporting init error to RAPID
Both
> Propagate error type in header when reporting init error to RAPID

- README.md
- awslambdaric/bootstrap.py
- awslambdaric/lambda_runtime_marshaller.py
- setup.py
- tests/integration/codebuild/buildspec.os.alpine.yml
- tests/integration/codebuild/buildspec.os.amazonlinux.2.yml
- tests/integration/codebuild/buildspec.os.amazonlinux.2023.yml
- tests/integration/codebuild/buildspec.os.debian.yml
- tests/integration/codebuild/buildspec.os.ubuntu.yml
- tests/integration/docker/Dockerfile.echo.alpine
- tests/integration/docker/Dockerfile.echo.amazonlinux2
- tests/integration/docker/Dockerfile.echo.amazonlinux2023
- tests/integration/docker/Dockerfile.echo.debian
- tests/test_lambda_runtime_marshaller.py
#173 
- Add 3.13 as supported runtime.
- Both
> Add python3.13.

- awslambdaric/bootstrap.py
- awslambdaric/lambda_runtime_client.py
- awslambdaric/lambda_runtime_exception.py
- awslambdaric/lambda_runtime_hooks_runner.py
- requirements/base.txt
- tests/test_bootstrap.py
- tests/test_lambda_runtime_client.py
- tests/test_runtime_hooks.py
_Issue #, if available: NA
_Description of changes:
This adds the support for Snapstart Runtimes Hooks 
* Implements calls to `/restore/next` and `/restore/error` RAPID endpoints
* Implements execution of `beforeSnapshot` and `afterRestore` hooks
_Target (OCI, Managed Runtime, both): Both
> Add support for snapstart runtime hooks

- .pre-commit-config.yaml
- README.md
- RELEASE.CHANGELOG.md
- setup.py
_Issue #, if available: NA
_Description of changes:
This drops the support for deprecated python version that is from `python3.6` to `python3.8` will no longer be supported. This will be a major version bump as well 
_Target (OCI, Managed Runtime, both): Both
> Drop support for deprecated python versions

- awslambdaric/bootstrap.py
- tests/test_bootstrap.py
_Description of changes:_ Changing the warning message that's emitted when the user function raises an uncaught exception. This change addresses two problems with this warning:
- in Telemetry API the warning message arrives unquoted, making the event JSON invalid
- in CWL the warning message is always in text format, regardless of the log format configuration of the function
With this change
- the TelemetryAPI event will be a valid json
- the format of this warning message will match the format of any other logs the function produces
_Target (OCI, Managed Runtime, both):_ both
> Don't enforce text format on uncaught exception warning message
